package com.isuwang.soa.hello.domain;

import java.util.Optional;

/**
 * Autogenerated by Dapeng-Code-Generator (1.1.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 **/
public class Hello {

    /**
     *
     **/
    public String name;

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String name() {
        return this.name;
    }

    public Hello name(String name) {
        this.name = name;
        return this;
    }

    /**
     *
     **/
    public Optional<String> message = Optional.empty();

    public Optional<String> getMessage() {
        return this.message;
    }

    public void setMessage(Optional<String> message) {
        this.message = message;
    }

    public Optional<String> message() {
        return this.message;
    }

    public Hello message(Optional<String> message) {
        this.message = message;
        return this;
    }

    /**
     *
     **/
    public com.isuwang.soa.hello.enums.HelloEnum type;

    public com.isuwang.soa.hello.enums.HelloEnum getType() {
        return this.type;
    }

    public void setType(com.isuwang.soa.hello.enums.HelloEnum type) {
        this.type = type;
    }

    public com.isuwang.soa.hello.enums.HelloEnum type() {
        return this.type;
    }

    public Hello type(com.isuwang.soa.hello.enums.HelloEnum type) {
        this.type = type;
        return this;
    }


    public String toString() {
        StringBuilder stringBuilder = new StringBuilder("{");
        stringBuilder.append("\"").append("name").append("\":\"").append(this.name).append("\",");
        stringBuilder.append("\"").append("message").append("\":\"").append(this.message.isPresent() ? this.message.get() : null).append("\",");
        stringBuilder.append("\"").append("type").append("\":").append(this.type).append(",");

        stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
        stringBuilder.append("}");

        return stringBuilder.toString();
    }
}
      