package com.isuwang.soa.hello.enums;

/**
 * Autogenerated by Dapeng-Code-Generator (1.1.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 **/
public enum HelloEnum implements com.isuwang.org.apache.thrift.TEnum {

    /**
     *
     **/
    HELLOENUM1(1),

    /**
     *
     **/
    HELLOENUM2(2),

    /**
     *
     **/
    HELLOENUM3(3);


    private final int value;

    private HelloEnum(int value) {
        this.value = value;
    }

    public int getValue() {
        return this.value;
    }

    public static HelloEnum findByValue(int value) {
        switch (value) {

            case 1:
                return HELLOENUM1;

            case 2:
                return HELLOENUM2;

            case 3:
                return HELLOENUM3;

            default:
                return null;
        }
    }
}
      